name: sign in

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 1 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # set timezone
      - name: set timezone
        run: sudo timedatectl set-timezone Asia/Shanghai
      # install node
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      # add dep
      - name: Install dependencies
        run: yarn --frozen-lockfile
      # run custom task
      - name: run index
        run: yarn run test
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          SCKEY: ${{ secrets.SCKEY }}

